InventoryManagementSystem/InventoryManagementSystem/Controllers/LogInController.cs
using BusinessLayer.BusinessLogic;
using BusinessLayer.Interfaces;
using DataLayer.Models;
using System.Web.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class LogInController : Controller
    {
        private readonly Inventory_Management_systeamEntities _dbContext=new Inventory_Management_systeamEntities();
        private readonly ILoginBusinessLogic _loginBusinessLogic=new LoginBusinessLogic();
        public LogInController()
        {

        }
        // GET: LogIn
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LogIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LogIn(LogIn objUser)
        {

            string message = string.Empty;
            tbUser obj = new tbUser();
            if (ModelState.IsValid)
            {
                obj = _loginBusinessLogic.LoginUser(objUser);
                if (obj != null)
                {
                    Session["UserID"] = obj.UserId.ToString();
                    Session["Email"] = obj.Email.ToString();
                    Session["AuthenticatedUser"]= obj.FirstName.ToString();
                    return RedirectToAction("DisplayItems","Item");

                }
                else
                {
                    message = "Username and/or password is incorrect.";

                    ViewBag.Message = message;
                }
            }
            return View(obj);
        }

        public ActionResult LogOut()
        {
            Session["UserID"] = null;
            Session["Email"] = null;
            Session["AuthenticatedUser"] = null;
            return RedirectToAction("Login");
        }
    }
}

InventoryManagementSystem/InventoryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Inventory Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        #footer {
            height: 50px; 
        }

        #footer-content {
            background-color: #f3e5f5;
            border: 1px solid #ab47bc;
            height: 32px; 
            padding: 8px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="outernavigation">
        @if (Session["AuthenticatedUser"] != null)
        {
            <div class="container" id="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Inventory Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Display items", "DisplayItems", "Item")</li>
                        <li>@Html.ActionLink("Warehouse 1", "WarehouseOne", "Item")</li>
                        <li>@Html.ActionLink("Warehouse 2", "WarehouseTwo", "Item")</li>
                        <li>@Html.ActionLink("LogOut", "LogOut", "LogIn")</li>

                    </ul>
                </div>
            </div>
        }
        </div>
    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer id="footer">
            <div id="footer-content">
                &copy; @DateTime.Now.Year - My Inventory Application
                </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>